# Site settings
title: Oliver's Flamenco Blog
email: oliver@jaun.org
description: > # this means to ignore newlines until "baseurl:"
  Blog about flamenco in general and flamenco guitar
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://flamenco.jaun.org" # the base hostname & protocol for your site
#github_username:  olijaun
author: Oliver Jaun
author_about: /about
permalink: /blog/:year/:month/:title
# Build settings
markdown: kramdown
gems:
- jekyll-paginate
- jekyll-sitemap
paginate: 5
paginate_path: "/page:num/"
excerpt_separator: <!--more-->

sass:
    style: :compressed
